development:
  adapter: postgresql
  encoding: unicode
  database: task_app
  pool: 5
  username: task
  password: 123456
  host: localhost 

production:
  adapter: postgresql
  encoding: unicode
  database: task_app1
  pool: 5
  username: task
  password: 123456
  host: localhost 